<?php

namespace Database\Seeders;

use App\Models\Member;
use App\Models\VictoryGroup;
use Illuminate\Database\Seeder;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $victoryGroups = VictoryGroup::all();
        
        if ($victoryGroups->isEmpty()) {
            $this->command->warn('No victory groups found. Please run VictoryGroupSeeder first.');
            return;
        }

        $members = [
            // Makati Victory Group Members
            [
                'first_name' => 'Carlos',
                'middle_initial' => 'M',
                'last_name' => 'Rivera',
                'age' => 24,
                'sex' => 'Male',
                'contact_number' => '09171234501',
                'lifestage' => 'Single',
                'address' => '123 Makati Avenue, Makati City',
                'date_launched' => '2023-01-15',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Maria',
                'middle_initial' => 'L',
                'last_name' => 'Francisco',
                'age' => 22,
                'sex' => 'Female',
                'contact_number' => '09181234502',
                'lifestage' => 'Single',
                'address' => '456 Ayala Street, Makati City',
                'date_launched' => '2023-02-20',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Joshua',
                'middle_initial' => 'K',
                'last_name' => 'Tan',
                'age' => 26,
                'sex' => 'Male',
                'contact_number' => '09191234503',
                'lifestage' => 'Single',
                'address' => '789 BGC Boulevard, Taguig City',
                'date_launched' => '2022-11-10',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Catherine',
                'middle_initial' => 'J',
                'last_name' => 'Wong',
                'age' => 23,
                'sex' => 'Female',
                'contact_number' => '09161234504',
                'lifestage' => 'Single',
                'address' => '321 High Street, BGC, Taguig',
                'date_launched' => '2023-03-05',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Daniel',
                'middle_initial' => 'I',
                'last_name' => 'Gutierrez',
                'age' => 28,
                'sex' => 'Male',
                'contact_number' => '09151234505',
                'lifestage' => 'Married',
                'address' => '654 EDSA, Quezon City',
                'date_launched' => '2022-09-18',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Rachel',
                'middle_initial' => 'H',
                'last_name' => 'Cruz',
                'age' => 25,
                'sex' => 'Female',
                'contact_number' => '09171234506',
                'lifestage' => 'Single',
                'address' => '987 Commonwealth Avenue, Quezon City',
                'date_launched' => '2023-01-30',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Miguel',
                'middle_initial' => 'G',
                'last_name' => 'Hernandez',
                'age' => 27,
                'sex' => 'Male',
                'contact_number' => '09181234507',
                'lifestage' => 'Single',
                'address' => '159 Ortigas Avenue, Pasig City',
                'date_launched' => '2022-12-22',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Sophia',
                'middle_initial' => 'F',
                'last_name' => 'Lopez',
                'age' => 21,
                'sex' => 'Female',
                'contact_number' => '09191234508',
                'lifestage' => 'Single',
                'address' => '753 Shaw Boulevard, Mandaluyong City',
                'date_launched' => '2023-04-12',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Gabriel',
                'middle_initial' => 'E',
                'last_name' => 'Mendoza',
                'age' => 29,
                'sex' => 'Male',
                'contact_number' => '09161234509',
                'lifestage' => 'Married',
                'address' => '246 C5 Road, Taguig City',
                'date_launched' => '2022-08-07',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Isabella',
                'middle_initial' => 'D',
                'last_name' => 'Ramos',
                'age' => 20,
                'sex' => 'Female',
                'contact_number' => '09151234510',
                'lifestage' => 'Single',
                'address' => '135 Katipunan Avenue, Quezon City',
                'date_launched' => '2023-05-25',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Nathan',
                'middle_initial' => 'C',
                'last_name' => 'Perez',
                'age' => 31,
                'sex' => 'Male',
                'contact_number' => '09171234511',
                'lifestage' => 'Married',
                'address' => '468 Pioneer Street, Mandaluyong City',
                'date_launched' => '2022-06-14',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Victoria',
                'middle_initial' => 'B',
                'last_name' => 'Gonzales',
                'age' => 26,
                'sex' => 'Female',
                'contact_number' => '09181234512',
                'lifestage' => 'Single',
                'address' => '802 Julia Vargas Avenue, Pasig City',
                'date_launched' => '2023-02-03',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Samuel',
                'middle_initial' => 'A',
                'last_name' => 'Torres',
                'age' => 33,
                'sex' => 'Male',
                'contact_number' => '09191234513',
                'lifestage' => 'Married',
                'address' => '579 Alabang-Zapote Road, Muntinlupa City',
                'date_launched' => '2022-04-28',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Hannah',
                'middle_initial' => 'Z',
                'last_name' => 'Silva',
                'age' => 19,
                'sex' => 'Female',
                'contact_number' => '09161234514',
                'lifestage' => 'Single',
                'address' => '913 UP Diliman, Quezon City',
                'date_launched' => '2023-06-10',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Elijah',
                'middle_initial' => 'Y',
                'last_name' => 'Moreno',
                'age' => 30,
                'sex' => 'Male',
                'contact_number' => '09151234515',
                'lifestage' => 'Married',
                'address' => '147 Eastwood Avenue, Quezon City',
                'date_launched' => '2022-10-15',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Abigail',
                'middle_initial' => 'X',
                'last_name' => 'Castro',
                'age' => 24,
                'sex' => 'Female',
                'contact_number' => '09171234516',
                'lifestage' => 'Single',
                'address' => '258 Greenhills Shopping Center, San Juan',
                'date_launched' => '2023-03-20',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Benjamin',
                'middle_initial' => 'W',
                'last_name' => 'Flores',
                'age' => 27,
                'sex' => 'Male',
                'contact_number' => '09181234517',
                'lifestage' => 'Single',
                'address' => '369 Festival Mall, Muntinlupa City',
                'date_launched' => '2022-12-05',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Emily',
                'middle_initial' => 'V',
                'last_name' => 'Navarro',
                'age' => 22,
                'sex' => 'Female',
                'contact_number' => '09191234518',
                'lifestage' => 'Single',
                'address' => '741 Rizal Park, Manila',
                'date_launched' => '2023-04-08',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Jacob',
                'middle_initial' => 'U',
                'last_name' => 'Sandoval',
                'age' => 32,
                'sex' => 'Male',
                'contact_number' => '09161234519',
                'lifestage' => 'Married',
                'address' => '852 Market! Market!, Taguig City',
                'date_launched' => '2022-07-19',
                'status' => 'Inactive',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
            [
                'first_name' => 'Grace',
                'middle_initial' => 'T',
                'last_name' => 'Valdez',
                'age' => 25,
                'sex' => 'Female',
                'contact_number' => '09151234520',
                'lifestage' => 'Single',
                'address' => '963 Robinsons Galleria, Ortigas',
                'date_launched' => '2023-01-12',
                'status' => 'Active',
                'victory_group_id' => $victoryGroups->random()->id,
            ],
        ];

        foreach ($members as $memberData) {
            Member::create($memberData);
        }
    }
}